import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My practice App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between bg-cyan-500 p-5 text-white">
          <Link href="/custompage"> Custom Page</Link>
          <Link href="/render-context">Render Context</Link>
          <Link href="/sectionproduct">Section Product</Link>
          <Link href="/render-context">Render Context</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
